version: "3.8"

services:
  mywebsite-dev:
    hostname: mywebsite
    build:
      context: .
      target: dev-container
    volumes:
      - ./:/app/:delegated
    working_dir: /app/mywebsite
    user: root
    container_name: my_website
    ports:
      - "8000:8000"
    command: runserver 0.0.0.0:8000
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mywebsite:
    hostname: mywebsite
    build:
      context: .
      target: prod-container
#    volumes:
#      - ./mywebsite/static:/backend/static
    working_dir: /app/mywebsite
    user: root
    container_name: my_website
    ports:
      - "8000:8000"
    command: uwsgi --ini /app/uwsgi.ini
    networks:
      - default

  psql:
    image: postgres:14-alpine
    container_name: postgres
    hostname: psql
    environment:
      - POSTGRES_PASSWORD=website
      - POSTGRES_USER=website
    networks:
      - default
    ports:
      - "0.0.0.0:5432:5432/tcp"